package auth

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"time"

	"itab-backend/internal/database"
	"itab-backend/internal/models"

	"github.com/golang-jwt/jwt/v5"
)

var JWTSecret = []byte("itab-backend-secret-key-2024")

// Claims JWT声明
type Claims struct {
	UserID   uint   `json:"user_id"`
	Username string `json:"username"`
	IsAdmin  bool   `json:"is_admin"`
	jwt.RegisteredClaims
}

// GenerateToken 生成JWT token
func GenerateToken(user *models.User) (string, error) {
	claims := Claims{
		UserID:   user.ID,
		Username: user.Username,
		IsAdmin:  user.IsAdmin,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(JWTSecret)
}

// ParseToken 解析JWT token
func ParseToken(tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(token *jwt.Token) (interface{}, error) {
		return JWTSecret, nil
	})
	if err != nil {
		return nil, err
	}

	if claims, ok := token.Claims.(*Claims); ok && token.Valid {
		return claims, nil
	}

	return nil, errors.New("invalid token")
}

// GenerateRandomString 生成随机字符串
func GenerateRandomString(length int) string {
	bytes := make([]byte, length)
	rand.Read(bytes)
	return hex.EncodeToString(bytes)[:length]
}

// GenerateAccessKey 生成访问密钥对
func GenerateAccessKey() (accessKey, secretKey string) {
	accessKey = "AK" + GenerateRandomString(30)
	secretKey = "SK" + GenerateRandomString(62)
	return
}

// ValidateAccessKey 验证访问密钥
func ValidateAccessKey(accessKey, secretKey string) (*models.AccessKey, error) {
	var ak models.AccessKey
	err := database.DB.Preload("User").Where("access_key = ? AND secret_key = ?", accessKey, secretKey).First(&ak).Error
	if err != nil {
		return nil, errors.New("invalid access key")
	}

	// 检查是否已手动过期
	if ak.IsExpired {
		return nil, errors.New("access key has been expired")
	}

	// 检查是否过期
	if ak.ExpiresAt != nil && ak.ExpiresAt.Before(time.Now()) {
		return nil, errors.New("access key has expired")
	}

	return &ak, nil
}

// InitMasterUser 初始化主用户
func InitMasterUser(username, password string, autoGenerated bool) error {
	var count int64
	database.DB.Model(&models.User{}).Where("username = ?", username).Count(&count)

	if count > 0 {
		// 用户已存在，更新密码
		return database.DB.Model(&models.User{}).Where("username = ?", username).Updates(map[string]interface{}{
			"password":        password,
			"is_admin":        true,
			"need_change_pwd": autoGenerated,
		}).Error
	}

	// 创建新用户
	user := &models.User{
		Username:      username,
		Password:      password,
		IsAdmin:       true,
		NeedChangePwd: autoGenerated,
	}
	return database.DB.Create(user).Error
}

// NeedCreateMasterUser 检查是否需要创建管理员用户（数据库中没有任何用户时返回 true）
func NeedCreateMasterUser() bool {
	var count int64
	database.DB.Model(&models.User{}).Count(&count)
	return count == 0
}
