package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	"itab-backend/internal/auth"
	"itab-backend/internal/database"
	"itab-backend/internal/logger"
	"itab-backend/internal/router"
)

func main() {
	// 命令行参数
	user := flag.String("user", "", "管理员用户名")
	pwd := flag.String("pwd", "", "管理员密码")
	port := flag.Int("port", 8445, "服务端口")
	dbPath := flag.String("db", "./data/itab.db", "数据库路径")
	logDir := flag.String("log-dir", "./logs", "日志目录")
	logKeepDays := flag.Int("log-keep-days", 3, "日志保留天数，0表示永久保留")
	flag.Parse()

	// 初始化日志系统
	if err := logger.InitLogger(*logDir, *logKeepDays); err != nil {
		log.Fatalf("日志系统初始化失败: %v", err)
	}
	defer logger.Close()

	// 启动日志轮转
	logger.StartLogRotation()

	// 确保数据目录存在
	if err := os.MkdirAll("./data", 0755); err != nil {
		log.Fatalf("创建数据目录失败: %v", err)
	}

	// 确保静态文件目录存在
	if err := os.MkdirAll("./static", 0755); err != nil {
		log.Fatalf("创建静态文件目录失败: %v", err)
	}

	// 初始化数据库
	if err := database.InitDB(*dbPath); err != nil {
		log.Fatalf("数据库初始化失败: %v", err)
	}

	// 初始化管理员用户
	autoGenerated := false
	masterUser := *user
	masterPwd := *pwd

	if masterUser == "" || masterPwd == "" {
		// 自动生成用户名密码
		masterUser = "master"
		masterPwd = auth.GenerateRandomString(12)
		autoGenerated = true
		log.Println("========================================")
		log.Println("自动生成管理员账户:")
		log.Printf("用户名: %s", masterUser)
		log.Printf("密码: %s", masterPwd)
		log.Println("请登录后立即修改密码!")
		log.Println("========================================")
	}

	if err := auth.InitMasterUser(masterUser, masterPwd, autoGenerated); err != nil {
		log.Fatalf("初始化管理员用户失败: %v", err)
	}

	// 启动服务
	r := router.SetupRouter()
	addr := fmt.Sprintf(":%d", *port)
	log.Printf("服务启动在 http://localhost%s", addr)
	if err := r.Run(addr); err != nil {
		log.Fatalf("服务启动失败: %v", err)
	}
}
